"""recreate locations_images

Revision ID: 5434e60c917d
Revises: 6a436220a160
Create Date: 2022-05-19 00:03:52.702138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5434e60c917d'
down_revision = '6a436220a160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations_images',
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['image'], ['files.filename'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image', 'location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations_images')
    # ### end Alembic commands ###
