"""add x & y coords to Location

Revision ID: 547ad77f2238
Revises: 7712847f1a4f
Create Date: 2022-05-23 16:58:31.423107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547ad77f2238'
down_revision = '7712847f1a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('coord_x', sa.Float(precision=8), nullable=False))
    op.add_column('locations', sa.Column('coord_y', sa.Float(precision=8), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'coord_y')
    op.drop_column('locations', 'coord_x')
    # ### end Alembic commands ###
