"""delete locations_images

Revision ID: 6a436220a160
Revises: 6f6dd110b6cd
Create Date: 2022-05-19 00:02:40.345662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a436220a160'
down_revision = '6f6dd110b6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations_images',
    sa.Column('location_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image'], ['files.filename'], name='locations_images_image_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='locations_images_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', name='locations_images_pkey')
    )
    # ### end Alembic commands ###
