"""update location image

Revision ID: 6f6dd110b6cd
Revises: 5f2d8fcb98fa
Create Date: 2022-05-18 23:56:18.548540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f6dd110b6cd'
down_revision = '5f2d8fcb98fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('locations_images_location_id_fkey', 'locations_images', type_='foreignkey')
    op.drop_constraint('locations_images_author_id_fkey', 'locations_images', type_='foreignkey')
    op.create_foreign_key(None, 'locations_images', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'locations_images', 'files', ['image'], ['filename'], ondelete='CASCADE')
    op.drop_column('locations_images', 'author_id')
    op.drop_column('locations_images', 'uploaded_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations_images', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('locations_images', sa.Column('author_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'locations_images', type_='foreignkey')
    op.drop_constraint(None, 'locations_images', type_='foreignkey')
    op.create_foreign_key('locations_images_author_id_fkey', 'locations_images', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('locations_images_location_id_fkey', 'locations_images', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
