"""add phone number to User

Revision ID: 7712847f1a4f
Revises: 5434e60c917d
Create Date: 2022-05-23 15:53:55.495919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7712847f1a4f'
down_revision = '5434e60c917d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=15), nullable=True))
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
